# Generated by Django 4.2.7 on 2023-11-09 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "matchID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("startTime", models.DateTimeField(null=True)),
                ("endTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMatchRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeAlive", models.IntegerField(db_index=True, default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pong_backend_app.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "matches",
                    models.ManyToManyField(
                        related_name="players",
                        through="pong_backend_app.PlayerMatchRelation",
                        to="pong_backend_app.match",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playermatchrelation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pong_backend_app.user"
            ),
        ),
        migrations.AddIndex(
            model_name="playermatchrelation",
            index=models.Index(fields=["timeAlive"], name="timeAlive_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="playermatchrelation", unique_together={("user", "match")},
        ),
    ]
